按键上标前景样式: &ub
  fontSize: 0.88em
  offset:
    x: 0
    y: -8
  normalColor: ffffff
  highlightColor: ffffff

按键文字前景样式: &py
  fontSize: 0.75em
  offset:
    x: 0
    y: 35
  normalColor: FFFFFF
  highlightColor: FFFFFF

keyboard:
  style: keyboardStyle
  subviews:
    - HStack:
        subviews:
          - Cell: hamsterButton
          - Cell: uploadButton
          - Cell: scriptButton
          - Cell: fileButton
    - HStack:
        subviews:
          - Cell: skinButton
          - Cell: soundsButton
          - Cell: backupButton
          - Cell: deployButton

floatTargetScale:
  x: 0.45
  y: 0.7

keyboardStyle:
  insets: {top: 8, left: 8, bottom: 8, right: 8}
  backgroundStyle: keyboardBackgroundStyle

keyboardBackgroundStyle:
  type: original
  normalColor: 313131dd
  cornerRadius: 8
  borderSize: 0.5
  normalBorderColor: 22222255
  normalLowerEdgeColor: 55555555

hamsterButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - hamsterButtonForegroundStyle1
    - hamsterButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/main}

hamsterButtonForegroundStyle1:
  systemImageName: keyboard
  <<: *ub

hamsterButtonForegroundStyle2:
  text: 设置
  <<: *py

uploadButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - uploadButtonForegroundStyle1
    - uploadButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/uploadInputSchema}

uploadButtonForegroundStyle1:
  systemImageName: wifi
  <<: *ub

uploadButtonForegroundStyle2:
  text: 上传
  <<: *py

soundsButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - soundsButtonForegroundStyle1
    - soundsButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/feedback}

soundsButtonForegroundStyle1:
  systemImageName: speaker.wave.2
  <<: *ub

soundsButtonForegroundStyle2:
  text: 声音
  <<: *py

scriptButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - scriptButtonForegroundStyle1
    - scriptButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/clipboard?type=script}

scriptButtonForegroundStyle1:
  systemImageName: terminal
  <<: *ub

scriptButtonForegroundStyle2:
  text: 脚本
  <<: *py

skinButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - skinButtonForegroundStyle1
    - skinButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/keyboardSkins}

skinButtonForegroundStyle1:
  systemImageName: tshirt
  <<: *ub

skinButtonForegroundStyle2:
  text: 皮肤
  <<: *py

fileButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - fileButtonForegroundStyle1
    - fileButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/finder}

fileButtonForegroundStyle1:
  systemImageName: folder
  <<: *ub

fileButtonForegroundStyle2:
  text: 文件
  <<: *py

backupButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - backupButtonForegroundStyle1
    - backupButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/backup}

backupButtonForegroundStyle1:
  systemImageName: person.icloud
  <<: *ub

backupButtonForegroundStyle2:
  text: 备份
  <<: *py

deployButton:
  size:
    height: 1/4
  backgroundStyle: ButtonBackgroundStyle
  foregroundStyle:
    - deployButtonForegroundStyle1
    - deployButtonForegroundStyle2
  action: {openURL: hamster://dev.fuxiao.app.hamster/rime?deploy}

deployButtonForegroundStyle1:
  systemImageName: arrow.2.circlepath
  <<: *ub

deployButtonForegroundStyle2:
  text: 部署
  <<: *py

# 按键背景
ButtonBackgroundStyle:
  animation: BackgroundAnimation
  normalImage:
    file: 26key
    image: IMG1
  highlightImage:
    file: 26key_press
    image: IMG1
  targetScale: 0.89

# 按键背景动画
ButtonBackgroundAnimation:
  - type: bounds
    duration: 60 # 动画时长，单位毫秒
    repeatCount: 1
    fromScale: 1
    toScale: 0.87
  - type: bounds
    duration: 80
    repeatCount: 1
    fromScale: 0.87
    toScale: 1

# 按键前景动画
ButtonForegroundAnimation:
  - type: bounds
    duration: 60 # 动画时长，单位毫秒
    repeatCount: 1
    fromScale: 1
    toScale: 0.87
  - type: bounds
    duration: 80
    repeatCount: 1
    fromScale: 0.87
    toScale: 1
