#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Move cross-file same-code groups into an early short-first dictionary.

For codes where active import order puts a longer word before a shorter word in
another dictionary, this script:
1. Creates/updates xmjd6.same_code_short_first.dict.yaml with the whole code
   group sorted by word length (stable within same length).
2. Removes those exact entries from their original dictionaries.
3. Ensures xmjd6.extended.dict.yaml imports the priority dictionary immediately
   after xmjd6.wxw. It must not sit above the 630/wxw dictionary.

No Lua is used.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

PRIORITY_NAME = "xmjd6.same_code_short_first"
PRIORITY_FILE = Path(PRIORITY_NAME + ".dict.yaml")
EXTENDED_FILE = Path("xmjd6.extended.dict.yaml")
EXCLUDES = {
    "english.dict.yaml",
    "pinyin_simp.dict.yaml",
    "liangfen.dict.yaml",
    "xmjd6.en.dict.yaml",
    "xmjd6.gbk.dict.yaml",
}


@dataclass(frozen=True)
class Entry:
    order: int
    path: Path
    line_no: int
    line: str
    word: str
    code: str
    length: int


def parse_entry(line: str) -> tuple[str, str] | None:
    body = line.rstrip("\r\n")
    stripped = body.strip()
    if not stripped or stripped.startswith("#") or stripped in {"---", "..."}:
        return None
    if "\t" not in body:
        return None
    parts = body.split("\t")
    if len(parts) < 2:
        return None
    word = parts[0].strip()
    code = parts[1].strip()
    if not word or not code:
        return None
    return word, code


def active_import_files(include_priority: bool = False) -> list[Path]:
    files: list[Path] = []
    in_import = False
    for line in EXTENDED_FILE.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        if line.strip() == "import_tables:":
            in_import = True
            continue
        if not in_import:
            continue
        match = re.match(r"^\s*-\s*([A-Za-z0-9_.]+)\b", line)
        if not match:
            continue
        path = Path(match.group(1) + ".dict.yaml")
        if path.name in EXCLUDES:
            continue
        if path == PRIORITY_FILE and not include_priority:
            continue
        if path.exists():
            files.append(path)
    return files


def scan_entries(files: list[Path]) -> list[Entry]:
    entries: list[Entry] = []
    order = 0
    for path in files:
        for line_no, line in enumerate(path.read_text(encoding="utf-8-sig", errors="replace").splitlines(keepends=True), 1):
            parsed = parse_entry(line)
            if parsed is None:
                continue
            word, code = parsed
            entries.append(Entry(order, path, line_no, line, word, code, len(word)))
            order += 1
    return entries


def bad_groups(entries: list[Entry]) -> dict[str, list[Entry]]:
    by_code: dict[str, list[Entry]] = defaultdict(list)
    for entry in entries:
        by_code[entry.code].append(entry)

    bad: dict[str, list[Entry]] = {}
    for code, group in by_code.items():
        min_after = 10**9
        has_bad = False
        for entry in reversed(group):
            if entry.length > min_after:
                has_bad = True
                break
            min_after = min(min_after, entry.length)
        if has_bad:
            bad[code] = group
    return bad


def priority_lines(groups: dict[str, list[Entry]]) -> list[str]:
    lines: list[str] = [
        "# Rime dictionary\n",
        "# encoding: utf-8\n",
        "#\n",
        "# Same-code short-first priority dictionary. Generated by move_cross_file_same_code_short_first.py\n",
        "---\n",
        f"name: {PRIORITY_NAME}\n",
        'version: "Q1"\n',
        "sort: original\n",
        "use_preset_vocabulary: false\n",
        "...\n",
    ]

    for code in sorted(groups):
        group = groups[code]
        lines.append(f"# code: {code}\n")
        seen: set[tuple[str, str, str]] = set()
        for entry in sorted(group, key=lambda item: (item.length, item.order)):
            normalized = entry.line if entry.line.endswith(("\n", "\r")) else entry.line + "\n"
            key = (entry.word, entry.code, normalized.rstrip("\r\n"))
            if key in seen:
                continue
            seen.add(key)
            lines.append(normalized)
    return lines


def ensure_priority_import() -> bool:
    text = EXTENDED_FILE.read_text(encoding="utf-8-sig", errors="replace")
    if re.search(rf"^\s*-\s*{re.escape(PRIORITY_NAME)}\b", text, flags=re.M):
        return False

    lines = text.splitlines(keepends=True)
    out: list[str] = []
    inserted = False
    for line in lines:
        out.append(line)
        if not inserted and line.strip() == "- xmjd6.wxw":
            out.append(f"  - {PRIORITY_NAME}  # 同码候选短词优先（自动整理生成，需在 wxw 后面）\n")
            inserted = True
    if not inserted:
        raise SystemExit("xmjd6.wxw import not found in xmjd6.extended.dict.yaml")
    EXTENDED_FILE.write_text("".join(out), encoding="utf-8")
    return True


def remove_original_entries(groups: dict[str, list[Entry]]) -> tuple[int, int]:
    remove_by_path: dict[Path, set[int]] = defaultdict(set)
    for group in groups.values():
        for entry in group:
            if entry.path == PRIORITY_FILE:
                continue
            remove_by_path[entry.path].add(entry.line_no)

    changed_files = 0
    removed_lines = 0
    for path, line_numbers in remove_by_path.items():
        lines = path.read_text(encoding="utf-8-sig", errors="replace").splitlines(keepends=True)
        new_lines = [line for index, line in enumerate(lines, 1) if index not in line_numbers]
        if len(new_lines) != len(lines):
            path.write_text("".join(new_lines), encoding="utf-8")
            changed_files += 1
            removed_lines += len(lines) - len(new_lines)
    return changed_files, removed_lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    files = active_import_files(include_priority=False)
    entries = scan_entries(files)
    groups = bad_groups(entries)
    priority_entry_count = sum(len(group) for group in groups.values())

    print(f"active files: {len(files)}")
    print(f"cross-file/global bad groups: {len(groups)}")
    print(f"entries to move into priority dict: {priority_entry_count}")

    if not args.apply:
        print("dry-run only; use --apply to rewrite dictionaries")
        return 0

    PRIORITY_FILE.write_text("".join(priority_lines(groups)), encoding="utf-8")
    inserted = ensure_priority_import()
    changed_files, removed_lines = remove_original_entries(groups)

    print(f"wrote: {PRIORITY_FILE}")
    print(f"inserted import: {inserted}")
    print(f"changed original files: {changed_files}")
    print(f"removed original lines: {removed_lines}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
