name: 微信绿·TF版·文字
author:

fontFace:
#- name: PingFangSC-Regular
- url: kafei.ttf
- name: PingFangSC-Medium
- url: TumanPUA.ttf
- url: SymbolsNerdFont-Regular.ttf

# 中文键盘
pinyin:
  iPhone:
    portrait: pinyin_26_portrait
    landscape: pinyin_26_landscape
  iPad:
    portrait: iPad_pinyin_26_portrait
    landscape: iPad_pinyin_26_landscape
    floating: iPad_pinyin_26_float

# 英文键盘
alphabetic:
  iPhone:
    portrait: alphabetic_26_portrait
    landscape: alphabetic_26_landscape
  iPad:
    portrait: iPad_pinyin_26_portrait
    landscape: iPad_pinyin_26_landscape
    floating: iPad_pinyin_26_float

# 数字键盘
numeric:
  iPhone:
    portrait: numeric_9_portrait
    landscape: pinyin_26_landscape
  iPad:
    portrait: iPad_numeric_26_portrait
    landscape: iPad_numeric_26_landscape
    floating: numeric_9_portrait

# 符号键盘
symbolic:
  iPhone:
    portrait: symbolic_portrait
    landscape: symbolic_landscape
  iPad:
    portrait: iPad_symbolic_portrait
    landscape: iPad_symbolic_landscape
    floating: iPad_symbolic_float

# 搜索浮动键盘
floatsearch:
  iPhone:
    portrait: floatsearch_portrait
    landscape: floatsearch_landscape

# 设置浮动键盘
floatconfig:
  iPhone:
    portrait: floatconfig_portrait
    landscape: floatconfig_landscape

# switch键盘
floatswitch:
  iPhone:
    portrait: floatswitch_portrait
    landscape: floatswitch_landscape

#表情键盘
emoji:
  iPhone:
    portrait: emoji_portrait
    landscape: emoji_landscape
  iPad:
    portrait: emoji_portrait
    landscape: emoji_landscape
    floating: emoji_float
